### ISSUE TITLE
Outsource Description not working on macOS

### ISSUE THREAD

**Issue by polizoto** [TUD-INF-IAI-MCI/agsbs_atom_package#287]
When checking the Outsource description checkbox (macOS) from the Insert image dialog box, there is no new markdown file generated after the dialog box is closed.

A link referring to the corresponding html file also is not created. Instead, only Markdown image syntax is created for the image.

`![Accessibility Icon](image.jpg)`

Instead of 

`[![Accessibility Icon](image.jpg)](./bilder.html#Accessibility)`

**Comment by jevo** [comment]
Thx for finding and reporting this bug. It is fixed and it will by part of the next release.
